apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: "rsyslog"
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - hard
    - rw
  nfs:
    path: /
    server: 192.168.10.14
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: "rsyslog"
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-csi"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
