apiVersion: v1
kind: Service
metadata:
  name: "rsyslog"
  namespace: "rsyslog"
spec:
  ports:
    - port: 514
      targetPort: 514
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "rsyslog"
  loadBalancerIP: 192.168.10.201
